/********************************************************************************
* bg_Active_Campaign_Checker_Controller :
*
* Controller for lead inline visualforce page to check -
* - whether an active campaign is in range of a lead
*
* Created By: Hossein Mirzapour 
* Created Date: 02-10-2015 
*
* Changes:
*********************************************************************************/

public without sharing class bg_Active_Campaign_Checker_Controller {

}