/**********************************************************
* bg_Active_Campaign_Checker_Test :
*
* Tests for the lead Controller for inline visualforce page to check -
* - whether an active campaign is in range of a lead
*
* Created By: Hossein Mirzapour 
* Created Date: 02-10-2015 
*
* Changes:
*
**********************************************************/

@isTest
public class bg_Active_Campaign_Checker_Test {

 //Dummmying the code as the geopint is uninstalled   

}