/**********************************************************
*
* bg_Constants:
*
* Hold String constants
*
* Created By: Hossein Mirzapour 
* Created Date: 02-10-2015 
*
* Changes:
*
**********************************************************/

public class bg_Constants {

	// Record type names
	public static final String RECORD_TYPE_SEMINAR_CONFERENCE = 'Seminar / Conference';
	public static final String QMS_ACCOUNT_RECORDTYPE = 'QMS';
	public static final String QMS_OPPORTUNITY_RECORDTYPE = 'QMS';
	public static final String CITATION_ACCOUNT_RECORDTYPE = 'Citation';
	public static final String CITATION_OPPORTUNITY_RECORDTYPE = 'Default_Citation_Opportunity';
	public static final String QMS_QUOTE_RECORDTYPE = 'QMS_Quote';
	public static final String DEFAULT_QUOTE_RECORDTYPE = 'Default_Quote';
	public static final String STANDARD_CONTRACT_RECORDTYPE = 'Standard_Contract';

	// Opportunity Stages
	public static final String OPPORTUNITY_STAGE_QUOTEDQMS = 'Quoted QMS';
	public static final String OPPORTUNITY_STAGE_APPOINTMENT = 'Appointment';
	public static final String OPPORUNITY_STAGE_CLOSED_WON = 'Closed Won';
	public static final String OPPORUNITY_STAGE_CLOSED_LOST = 'Closed Lost';
	public static final String OPPORUNITY_STAGE_RENEWALDUE = 'Renewal Contact Due';

	// Opportunity Types
	public static final String RENEWAL_OPPORTUNITY_TYPE = 'Renewal';

	// Opportunity Certification Options
	public static final String OPPORTUNITY_CERTIFICATION_CONNECT = 'Connect Existing Customer';

	// Product Special Types
	public static final String REDUCTION_PRODUCT_TYPE = 'Reduction';

	//GA Integration
	public static final String ACCOUNT_ACTIVATION = 'Account Activation';
	public static final String ACCOUNT_DEACTIVATION = 'Account Deactivation';

	//Pricing calculator fields
	public static final String PRODUCT_COMBINED_SERVICE = 'Combined Service';
	public static final String PRODUCT_HEALTH_AND_SAFETY = 'Health & Safety';
	public static final String PRODUCT_EMPLOYMENT_LAW = 'Employment Law';

}