/**********************************************************************
* bg_Campaign_Helper:
*
* Helper class for methods on the Campaign
* Created By: Kash Hussain
* Created Date: 26-11-2015
*
* Changes: 
***********************************************************************/
public without sharing class bg_Campaign_Helper 
{    
	/*
		Method to check if the Campaign Location updates are required.
	*/
//Made this null when uninstalled geopoint managed package
}